name: Archive

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Zip archive
      run: zip inf585_code.zip ./* -r
    - name: Upload archive
      uses: actions/upload-artifact@v2
      with:
        name: realease
        path: inf585_code.zip
